apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
  labels:
    app: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: wisecow
          image: wisecow:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4499
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: false  # App needs to create fifo file
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: app-tmp
              mountPath: /app
          readinessProbe:
            tcpSocket:
              port: 4499
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 4499
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: app-tmp
          emptyDir: {}
