apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-monitor
  labels:
    app: health-monitor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: health-monitor
  labels:
    app: health-monitor
rules:
- apiGroups: [""]
  resources: ["pods", "services", "ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: health-monitor
  labels:
    app: health-monitor
subjects:
- kind: ServiceAccount
  name: health-monitor
  namespace: default
roleRef:
  kind: Role
  name: health-monitor
  apiGroup: rbac.authorization.k8s.io
